name: Coverage Workflow
on:
  pull_request:

jobs:
  coverage-report:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node.js dependencies
        run: npm install

      - name: Lint code
        run: flake8 .

      - name: Run tests with coverage
        run: |
          coverage run -m pytest tests/
          coverage report
          coverage html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/
