name: CI Workflow
on:
  push:

jobs:
  run-linter-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node.js dependencies
        run: npm install

      - name: Lint code
        run: flake8 .

      - name: Debug CI/CD environment
        run: ls -R

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV

      - name: Run tests
        run: pytest tests/

      - name: Run Database Migrations
        run: alembic upgrade head
